**To - Do - 1:**
1. Read and Observe the Dataset.
2. Print top(5) and bottom(5) of the dataset {Hint: pd.head and pd.tail}.
3. Print the Information of Datasets. {Hint: pd.info}.
4. Gather the Descriptive info about the Dataset. {Hint: pd.describe}
5. Split your data into Feature (X) and Label (Y).

In [2]:
import pandas as pd
data =pd.read_csv("/content/drive/MyDrive/week-4/student.csv")
data

     Math  Reading  Writing
0      48       68       63
1      62       81       72
2      79       80       78
3      76       83       79
4      59       64       62
..    ...      ...      ...
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

[1000 rows x 3 columns]

In [3]:
data.head()

   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [4]:
data.tail()

     Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB

In [6]:
data.describe()

              Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

In [7]:
# Assuming 'Math_score' is the label and the rest are features
X = data.drop('Math', axis=1)  # Features
Y = data['Math']  # Label
print("Features (X):")
print(X.head())

print("\nLabel (Y):")
print(Y.head())

Features (X):
   Reading  Writing
0       68       63
1       81       72
2       80       78
3       83       79
4       64       62

Label (Y):
0    48
1    62
2    79
3    76
4    59
Name: Math, dtype: int64

***To - Do - 2:***
1. To make the task easier - let’s assume there is no bias or intercept.
2. Create the following matrices:

Y = WTX

In [8]:
import numpy as np

# Extract features and label
X = data.drop('Math', axis=1).values.T  # Transpose to match shape (d x n)
Y_actual = data['Math'].values  # Actual labels

# Initialize weight matrix (random values for illustration)
d = X.shape[0]  # Number of features
W = np.random.rand(d, 1)  # Weight vector of shape (d x 1)

# Compute predicted Y (Y = W^T X)
Y_pred = np.dot(W.T, X)  # Shape: (1 x n)

# Print the matrices
print("Feature Matrix (X):")
print(X[:, :5])  # Display first 5 samples

print("\nWeight Matrix (W):")
print(W)

print("\nPredicted Label Vector (Y):")
print(Y_pred[:, :5])  # Display predictions for first 5 samples

Feature Matrix (X):
[[68 81 80 83 64]
 [63 72 78 79 62]]

Weight Matrix (W):
[[0.60272869]
 [0.74836454]]

Predicted Label Vector (Y):
[[ 88.13251731 102.7032712  106.59072977 109.14728039  84.973238  ]]

**• To - Do - 3:**
1. Split the dataset into training and test sets.
2. You can use an 80-20 or 70-30 split, with 80% (or 70%) of the data used for training and the rest
for testing.

In [9]:
import numpy as np

# Shuffle the dataset to ensure randomness
data = data.sample(frac=1, random_state=42).reset_index(drop=True)  # Shuffles the data

# Features and labels
X = data.drop('Math', axis=1).values  # Features as NumPy array
Y = data['Math'].values  # Labels as NumPy array

# Define the split ratio
split_ratio = 0.8  # 80-20 split (use 0.7 for 70-30 split)
split_index = int(len(X) * split_ratio)

# Split the data
X_train, X_test = X[:split_index], X[split_index:]
Y_train, Y_test = Y[:split_index], Y[split_index:]

# Print the shapes to verify the split
print("Training Features (X_train):", X_train.shape)
print("Test Features (X_test):", X_test.shape)
print("Training Labels (Y_train):", Y_train.shape)
print("Test Labels (Y_test):", Y_test.shape)

Training Features (X_train): (800, 2)
Test Features (X_test): (200, 2)
Training Labels (Y_train): (800,)
Test Labels (Y_test): (200,)

**To - Do:4**
We will define a function that:
1. Loads the data and splits it into training and test sets.
2. Prepares the feature matrix (X) and target vector (Y).
3. Defines the weight matrix (W) and initializes the learning rate and number of iterations.
4. Calls the gradient descent function to learn the parameters.
5. Evaluates the model using RMSE and R2

In [10]:
def train_and_evaluate_model(data, learning_rate=0.01, num_iterations=1000):
    # Prepare the data
    X = data.drop('Math', axis=1).values
    Y = data['Math'].values.reshape(-1, 1)  # Reshape Y to a column vector

    # Normalize features (important for gradient descent)
    X_mean = np.mean(X, axis=0)
    X_std = np.std(X, axis=0)
    X = (X - X_mean) / X_std

    # Split the data
    split_ratio = 0.8
    split_index = int(len(X) * split_ratio)
    X_train, X_test = X[:split_index], X[split_index:]
    Y_train, Y_test = Y[:split_index], Y[split_index:]

    # Initialize weights
    num_features = X_train.shape[1]
    W = np.random.rand(num_features, 1)  # Initialize weights randomly


    # Gradient descent function (implementation not shown but assumed to exist)
    def gradient_descent(X, Y, W, learning_rate, num_iterations):
      for _ in range(num_iterations):
          # Calculate predictions
          Y_pred = np.dot(X, W)

          # Calculate the error
          error = Y_pred - Y

          # Calculate the gradient
          gradient = np.dot(X.T, error) / len(X)

          # Update weights
          W = W - learning_rate * gradient

      return W

    W = gradient_descent(X_train, Y_train,W, learning_rate, num_iterations)

    # Make predictions on test data
    Y_pred_test = np.dot(X_test, W)


    # Evaluate the model
    def rmse(y_true, y_predicted):
        return np.sqrt(np.mean((y_true - y_predicted)**2))

    def r2_score(y_true, y_predicted):
        mean_y_true = np.mean(y_true)
        ss_tot = np.sum((y_true - mean_y_true)**2)
        ss_res = np.sum((y_true - y_predicted)**2)
        r2 = 1 - (ss_res / ss_tot)
        return r2

    rmse_val = rmse(Y_test,Y_pred_test)
    r2 = r2_score(Y_test,Y_pred_test)

    print(f"RMSE: {rmse_val}")
    print(f"R^2: {r2}")

    return W # Return the trained weights

trained_weights = train_and_evaluate_model(data)

RMSE: 66.9812749097285
R^2: -19.28457319814459